# Generated by Django 5.2.15 on 2026-06-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('apply_url', models.URLField(max_length=500)),
                ('source', models.CharField(default='Web Scraper Engine', max_length=100)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
