# Generated by Django 5.2.15 on 2026-06-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoltan', '0002_scheduletask'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_mastered', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='zoltan.roadmaptrack')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
