# Generated by Django 4.2.30 on 2026-06-22 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoltan', '0003_roadmaptrack_roadmapmilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role_title', models.CharField(max_length=255)),
                ('status', models.CharField(default='Scheduled', max_length=100)),
                ('date_scheduled', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='zoltan.interviewpipeline')),
            ],
        ),
    ]
